apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: supported-postgres-version
  annotations: 
    title: "PostgreSQL Version Check"
    description: "Verify that a PostgreSQL server is running a compatible version"
    category: "database"
    iconUri: "/category-icons/postgres.svg"
    tags: '["database", "postgresql"]'
    contributors: '[{"name": "Marc Campbell", "avatarUri": "https://avatars3.githubusercontent.com/u/173451?s=460&v=4"}]'
spec:
  collectors:
    - postgres:
        collectorName: postgresql
        uri: postgresql://user:password@hostname:5432/dbname?sslmode=require
  analyzers:
    - postgres:
        checkName: Must be PostgreSQL 10.x or later
        collectorName: postgresql
        outcomes:
          - fail:
              when: "connected == false"
              message: Cannot connect to PostgreSQL server
          - fail:
              when: "version < 10.x"
              message: The PostgreSQL server must be at least version 10
          - pass:
              message: The PostgreSQL server is ready
  